### ISSUE TITLE
Teorico a empirico

### ISSUE THREAD

**Issue by dimusa6** [BorjaLive/ETSIcode#5]
¿No cambiaría de Teorico a Empirico en el script Empirico?

https://github.com/BorjaLive/ETSIcode/blob/89aadde0ab872a8eb7e0e3aa9fc60eaf2f23c628/FAA/Practica%201/Practica%201/CmdCompararEmpirico.gpl#L2

**Comment by BorjaLive** [comment]
Tienes razón, estoy revisando el resto de archivos gpl.
Esta incoherencia está solo a nivel de nombre, no debería afectar al dibujado.

**Comment by BorjaLive** [comment]
Ya he cambiado ese nombre, el resto de archivos gpl parecen correctos.
https://github.com/BorjaLive/ETSIcode/blob/62e7aba20c86df95f838b427f76f0ca4254e3545/FAA/Practica%201/Practica%201/CmdCompararEmpirico.gpl#L2
_Cierro el hilo._
