### ISSUE TITLE
Error en el ejercicio 13

### ISSUE THREAD

**Issue by pepec0de** [BorjaLive/ETSIcode#6]
Estoy haciendo las prácticas y me pasaron este repo y estoy usando estos scripts como referencia (para ver como quieren que programes). Tienes un error en el ejercicio 13.cpp (Primero/FP/Tema2/) declarando las vars de los coeficientes, no te pide que sean de tipo double, sino int.
Saludos.

PD: Ya se que esto da un poco igual pero supongo que quitaran nota. Escribo esto para los que copien directamente el codigo.

Mi script con la corrección:
![ej cpp](https://user-images.githubusercontent.com/24196306/97078828-3aa21580-15ef-11eb-99e1-5a2dee1369ba.png)

**Comment by BorjaLive** [comment]
Gracias por la ayuda.
Acabo de revisar el enunciado y tienes toda la razón, se pide que los valores de entrada sean de tipo entero.
Está resuelto en la [modificación más reciente del fichero](https://github.com/BorjaLive/ETSIcode/blame/master/Primero/FP/Tema2/13.cpp).
