### ISSUE TITLE
Error en el metodo bajaCliente() de la practica 1 de MP

### ISSUE THREAD

**Issue by pepec0de** [BorjaLive/ETSIcode#7]
Buenas Borja,
Creo que tienes un pequeño error en el metodo de bajaCliente() del fichero: [2 Segundo/MP/Practica1/src/Empresa.cpp](https://github.com/BorjaLive/ETSIcode/blob/master/2%20Segundo/MP/Practica1/src/Empresa.cpp)
En la línea 127 deberías implementar un bucle for en vez de un bucle while con estructura de búsqueda, te lo digo porque puede haber varios contratos con el mismo dni y en tu bucle no se está haciendo recorrido.
Un saludo crack.

**Comment by BorjaLive** [comment]
Es cierto que puede haber más de un contrato del mismo cliente y que hay que realizar un recorrido.
Pero si se hiciera con un for habría problemas por el funcionamiento de cancelarContrato. Cuando se cancela un contrato, se elimina del array y todos los contratos que le siguen se mueven una posición hacia para no dejar el hueco.
Habría que procurar no aumentar el índice si ocurre una eliminación, porque al desplazarse todo el array, nos saltaríamos el siguiente elemento. Modificar el índice manualmente en un for está contraindicado, así que es preferible usar un while, aunque se realice un recorrido.
![Ejemplo](https://user-images.githubusercontent.com/10326245/142226938-89cbc050-e80e-4b65-bbe1-292219921f05.png)

**Comment by pepec0de** [comment]
Tienes razón, habría problemas si se trabaja con el for.
